---
title: "Data Analysis Plan"
subtitle: "Data Analysis in R for Education Research"
author: "Rong Guang"
date: 2023-10-30
date-format: "D MMM YYYY"
published-title: "Created"
format: 
  html:
    embed-resources: true
toc: true
editor: 
  markdown: 
    wrap: sentence
---

# Modification description

## Comments from Marja

*A really good and completed plan and it's hard for me to come up with anything to fix it. Maybe you could think about whether the plan is too extensive to implement during the course and maybe put this as one of the risk factors. Think about possible solutions to this (leave some goals out if   necessary).*


## Modification made

I added the concerns about analysis progress in `Potential Risk` section. In addition, I gave solution that if the progress were going not as planned, which part of analysis would be dropped for the present analysis, so that the most fundamental research questions can still be answered.

# Data 

## Availability

I will use data from EVA Survey on Finnish Values and Attitudes Autumn 2020. 

The dataset was downloaded from Finnish Scoial Science Data Archive (link: https://services.fsd.tuni.fi/catalogue/FSD3494?lang=en&study_language=en). Anyone with the account of university of
helsinki is able to download it by applying. 

## My role in collecting data

I do not have any role in collecing the data. I got the idea of the meaning for relevant variables based on the handbook downloaded alongside the data. I will analyze the data for practicing R coding skills and finnishing the final task for the course.

## Describing the data

The study charted Finnish people's values and attitudes (n = 2019). The themes of the Autumn 2020 survey included the coronavirus (COVID-19) pandemic, financing the welfare state, happiness, equality, birth rate, and social problems. I will use a subset involving 37 variables (see figure 1) for the analysis. They have 4 categories: 
   
   a. happiness related items (14 items, answered on 5-tick likert scale);
   
      - an example: How important do you think "Experiences of love, to love and feel loved" are for 
        leading a happy life? Answer is from very important to not at all important
        
   b. alcohol related items (4 items, binary);
   
      - an example: Have you experienced/witnessed: Alcohol abuse - in your family/couple relationship
        Answer is yes or no.
        
   c. demographics (16 items, such as gender, age, residence, employer..);
   
   d. self-perceived happiness (1 item, answered on 5-tick likert scale)
   
      - example: How happy do you perceive your life to be at present? Do you think you are:
        Answer is from very happy to not at all happy

To check all the variables and levels please go to https://services.fsd.tuni.fi/catalogue/FSD3494?tab=variables&lang=en&study_language=en

## Ethical concern

The data was delabelled before uploading to the archive. I reported my purpose for using the data faithfully during applying for its access. Therefore, I believe there is no ethical issues. 

# Background and research question

Each year the UN releases a World Happiness Report showing which are the best countries to live in the world. 2023’s version has seen Finland come out in the top spot again. That is for the sixth year running. Meanwhile, it is interesting that Finland also has an alcohol problem. A 2020 study reported that, in the population of 5.5 million people in Finland, at least 270,000 Finns had experienced problems resulting from their own alcohol use in at least one area of life during the previous year. As such, I am very interested in digging into Fin’s sate of self-perceived happiness with the change of attitude towards happiness and self-perceived alcohol consumption change. Hence I formulate this research question: Whether attitude of happiness and alcohol usage influence Fin's self-perceived happiness? My hypothesis is both of them has their role in establishing a happy life. 

# Data analysis plan

## Data wrangling plan

The flowchart below shows the data wrangling for the present analysis (red box below). 

```{r class.source = 'fold-show'}
library(DiagrammeR)#install.packages("DiagrammeR"), a package for making flowchart 
DiagrammeR::grViz("digraph {
    graph [layout = dot, 
    rankdir = RR, 
    nodesep = 0.5, 
    ranksep = 0.8, 
    color = crimson, 
    penwidth =5]
     node [shape = 
     box, fontcolor = white, 
     fontsize=50, width = 3, 
     height = 1.5, 
     fillcolor = DimGrey, 
     style = filled]
    
  
    0 [label = 'Metadata', width = 14]
  
    1 [label = 'Q4', width =7]
    2 [label = 'Q7_1 to Q7_14', 
    width = 7]
    3 [label = 'Q11_4_1 to Q11_4_6', 
    width = 7]
    4 [label = 'T1 to T14, BV1, BV2', 
    width = 7]
    5 [label = 'Other Variables \n held out', 
    width = 7]
    1.5 [label = 'Self-perceived \n happiness (n = 1)', 
    width = 7]
    2.5 [label = 'Hhappiness \n attitude (n=14)', 
    width = 7]
    3.5[label = 'Alcohol abuse \n (n =6)', 
    width = 7]
    4.5[label = 'Demographics \n (n = 16)', 
    width = 7]
    6[label = 'New raw data set for analysis \n (variables n = 34, 
    cases n = 2019)', 
    width = 15]
    s1[label = 'Gernal Case Screening \n (n = 2019)', 
    width = 15]
    s2[label = 
    'Case Screening base on \n variables of major interest \n (n = ?)', 
    width = 15]
    s3[label = 
    'Final data set for analysis \n (variables n = ?, cases n = ?)', 
    width = 22.1]
    blanka[label = '', width = 0.01, height = 0.01]
    blankb[label = '', width = 0.01, height = 0.01]
    ss1[label = 
    'Remove cases \n with ≥ half (?) of \n the reponses being NA (n = ?)', 
    width = 10]
    ss2[label = 
    'Remove cases \n a. with any NA in self- perceived \n happiness  (dependent variable in \n modelling) (n = ?) \n b. with half (?) of the \nresponses  being NA in happiness \n attitude variables  (most-interested \n predictors in modelling) (n = ?)', 
    width = 8]
    0 -> {1 2 3 4};
    { rank = same;0 -> 5}
     subgraph cluster1 {
    1 -> 1.5;
    2 -> 2.5;
    3 -> 3.5;
    4 -> 4.5;
    {1.5 2.5 3.5 4.5} -> 6;}
   subgraph cluster2 {
    6 -> s1;
    s1 -> blanka[ dir = none, ranksep = 0.05 ];
    { rank = same; blanka -> ss1  [minlen = 2]};
    blanka -> s2 [ranksep = 0.05 ]; 
    s2 -> blankb[ dir = none ];
    { rank = same; blankb -> ss2 [minlen = 2]};
     blankb -> s3;}
}")
```

### Treating missing values

There are two major sources of NAs in the present data: a. respondents skipped to answer a questin; b. for likert-style item,"6" denotes "Can't say", and and it will be re-coded as NA. 

Missing values are present across the included variables. They will be treated to enhance the validity of study by the following rules: For the dependent variable in modelling (respondent's self-perceived happiness), cases with NA will be removed from analysis; For the most interested independent variables (variables about happiness, n = 14) that are plausibly correlated with demographic variables, any cases with more than half missing values (n of NAs ≥ 7) will be removed from analysis; any missing values for the cases kept will be imputed using Multiple Imputation Chain Equation (MICE) with all the other variables in the whole new data set being the predictors (except for indexing number); For alcohol-related variables and demographic variables, missing values will be kept as it is. Package "naniar", which aims at facilitating the missing value treatment process, will be used where appropriate. 

### Generating new variables

Items Q7_1 to Q7_14 asked about participant's perceived importance of 14 happiness sources. These items reflect their attitude towards happiness. I will try to derive latent constructs underlying them (using factor scores). The package ensemble "tidyverse" will be the used throughout this stage. 

### Re-naming and Re-coding

Continuous variables were read in as numeric, and they will be left as they are. Categorical variables were read in as strings, they will be converted into factors and a proper set of fix levels will be defined using "factor()". Ordinal variables' levels will be properly ordered. Variables will be re-named for better readability (perhaps first organized using "janitor::clean_names()"). Self-perceived happiness will be re-coded into a binary variable including happy and unhappy.

## Descriptives

Distributions (histogram) will be visualized for continuous variables. For normal variables, they will be described as mean ± sd; for categorical data, they will be described as Median (1st and 3rd quartiles). 

Absolute number with proportion will be reported for categorical data. Stacked bar plots will be used to visualize how a variable (x) changes with self-perceived happiness (y). 

For factor analysis of happiness specifically, Pearson correlation matrix will be generated to evaluate factorability. Cronbach's Alpha will be calculated to evaluate instrument reliability. Scree plot will be generated to determine the number of factors retained. 

After modeling, forest plot will be generated for demonstrating the effect of each predictors on response. 

Package "ggplot()" will be used across all visualization, except for model diagnostics (where base R "plot()" function will be used), scree plots and factor structure plots (where functions in psych package will be used), and forest plot (package "finalfit()" will be used).

## Analysis

### Overall description

### Factor analysis

In correlation matrix, $\gamma$ <0.3 items will be removed for factor analysis. Cronbach's $\alpha$ >0.6 will be regarded as being acceptable. Varimax rotation will be used considering the nature of the happiness items. Items with <0.3 factor loading will be removed. After each removal, the loadings based on new structure will be fitted.

Factor analysis and most relevant test/check-up (the only exception is correlation matirx)  will be realized using a number of functions in "psych" package .

### Logistic regression

Logistic regression will be used for modeling self-perceived happiness based on attitude of happiness (generated from factor score), alcohol usage, social economic status and demographic features. With the result I will try to answer the research question: if attitude of happiness and alcohol usage influence Fin's self-perceived happiness. 

Logistic regression presumes the linear relationship between the numeric predictors and predicted outcome. I will check if this is violated for any happiness attitude predictors using loess smoothing, especially for those insignificant in model, to evaluate if other modeling method is necessary to adopt.

If more than 50% of the variability can be explained by the model, I will go a step further from testing a hypothesis to establishing a classification model for telling happy and sad people by fine-tuning the model. But I don't place high expectation on it. 

Logistic regression will be realized using base R function.

## Learning goals

My top expectation is to improve the proficiency in coding. I am especially interested in exploring ways in treating missing values. I plan to use logistic regression by re-coding a 5-category ordinal variable into 2 levels. However, I will learn to use ordinal regression during the exercise. I did not write it down in the plan because I haven't thought it through. But I hope I can figure it out soon. Instead of practicing more packages, my hope is to practice using fewer packages. I will try using no more packages than those listed above, and perhaps fewer than listed (e.g. if possible, trying generating scree plot using "ggplot()").

## Potential risks

The researchers who collected the data did not base the happiness items on any existing scales, nor did they mention how they came up with it. There is a risk that they don't factor well. If the risk were realized, I will regard each item as a standalone variable and include them into the model. With this fairly large sample (n=2019), I believe it allows me to handle a few more predictors. 

Another potential risk is research progress. The analysis will be extensive in terms of the variables involved. If for some reason the analysis could not be progressed as planed, I would drop the variables about alcohol consumption and reduce the research question into "Whether attitude of happiness (removed part: and alcohol usage) influence Fin's self-perceived happiness?"
